const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const {PNG}=require('pngjs');
const jsQR=require('jsqr');
const {PDFDocument}=require('pdf-lib');
const {agentInput,qrImage,referralUrl,makeFlyer,placement}=require('../lib/agent-referrals.cjs');

test('CSV preserves quoted names, multiline notes and normalizes common headers',async()=>{
  const {parseAgentCsv}=await import('../agent-import.mjs');
  const rows=parseAgentCsv('First Name,Last Name,Email Address,Phone Number,Notes\r\nJane,Agent,JANE@example.com,9195550100,"Called, interested\nFollow up Friday"');
  assert.equal(rows[0].name,'Jane Agent');assert.equal(rows[0].notes,'Called, interested\nFollow up Friday');
  const normalized=agentInput(rows[0]);assert.equal(normalized.email,'JANE@example.com');assert.equal(normalized.phone,'9195550100');
  assert.throws(()=>parseAgentCsv('Name,Email\n"Jane,hello@example.com'),/closing quote/);
  const rich=parseAgentCsv('name,city,phone,phone_1,email_1,email_2,address,state,website\nJane,Durham,9195550100,9195550101,a@example.com,b@example.com,1 Main St,NC,https://example.com')[0];
  assert.equal(rich.email,'a@example.com');assert.equal(rich.phone_1,'9195550101');assert.equal(agentInput(rich).address,'1 Main St');
});

test('QR encodes the exact referral URL and PDF overlay preserves the template',async()=>{
  const code='TA-'+'A'.repeat(32),url=referralUrl(code);
  const image=PNG.sync.read(Buffer.from((await qrImage(code)).split(',')[1],'base64'));
  const decoded=jsQR(new Uint8ClampedArray(image.data),image.width,image.height);
  assert.equal(decoded.data,url);
  const doc=await PDFDocument.create();doc.addPage([612,792]).drawText('Turnly template content',{x:40,y:720,size:24});
  const source=await doc.save();
  const bytes=await makeFlyer(source,{qr_x:70,qr_y:68,qr_size:20},code);
  assert.equal((await PDFDocument.load(bytes)).getPageCount(),1);
  assert.ok(bytes.length>source.length);
  assert.throws(()=>placement({qr_x:95,qr_y:0,qr_size:20}),/fit/);
  const rotated=await PDFDocument.create();rotated.addPage([612,792]);rotated.addPage([612,792]);
  await assert.rejects(makeFlyer(await rotated.save(),{qr_x:70,qr_y:68,qr_size:20},code),/one-page/);
});

test('database preserves IDs, deduplicates customers, and earns only the first completed AND paid clean',async()=>{
  const db=new PGlite();const actor=randomUUID(),assignment=randomUUID(),invoice=randomUUID();
  try{
    await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
      create schema auth;create table auth.users(id uuid primary key);
      create table public.sales_leads(id uuid primary key default gen_random_uuid(),property_name text,name text,contact_name text,contact_email text,contact_phone text,address text,sales_city text,default_service_type text,lead_source text,lead_notes text,pipeline_stage text,next_step text,task_priority text,task_status text);
      create table public.quickbooks_invoice_links(id uuid primary key,quickbooks_status text,quickbooks_balance numeric,paid_at timestamptz);
      create table public.assignment_blocks(id uuid primary key,status text,quickbooks_invoice_link_id uuid references public.quickbooks_invoice_links(id));
      create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      grant usage on schema public,auth,storage to service_role;
      grant all on all tables in schema public to service_role;`);
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20261008120000_agent_referrals.sql'),'utf8'));
    await db.query('insert into auth.users values($1)',[actor]);
    const a=(await db.query("insert into referral_agents(name,email,status) values('Agent A','a@example.com','new') returning *")).rows[0];
    assert.equal(a.referral_code,null);
    const active=(await db.query("update referral_agents set status='active' where id=$1 returning *",[a.id])).rows[0];
    assert.match(active.referral_code,/^TA-[A-F0-9]{32}$/);
    await db.query("update referral_agents set status='not_interested' where id=$1",[a.id]);
    await db.query("update referral_agents set status='active',referral_code='forged' where id=$1",[a.id]);
    assert.equal((await db.query('select referral_code from referral_agents where id=$1',[a.id])).rows[0].referral_code,active.referral_code);
    const b=(await db.query("insert into referral_agents(name,email,status) values('Agent B','b@example.com','active') returning *")).rows[0];
    const register='select register_agent_referral($1,$2,$3,$4,$5,$6,$7)';
    await db.query(register,[active.referral_code,'Customer','CUSTOMER@example.com','+19195550100','1 Main St','Durham','Move in']);
    await db.query(register,[b.referral_code,'Customer','customer@example.com','+19195550101','1 Main St','Durham','Changed email']);
    await db.query(register,[b.referral_code,'Customer','other@example.com','+19195550100','1 Main St','Durham','Changed phone']);
    assert.equal((await db.query('select count(*)::int as n from referral_customers')).rows[0].n,1);
    assert.equal((await db.query('select count(*)::int as n from sales_leads')).rows[0].n,1);
    const customer=(await db.query('select * from referral_customers')).rows[0];assert.equal(customer.agent_id,a.id);
    await db.query("insert into quickbooks_invoice_links values($1,'open',200,null)",[invoice]);
    await db.query("insert into assignment_blocks values($1,'scheduled',$2)",[assignment,invoice]);
    await db.query('update referral_customers set first_assignment_id=$1,eligible_subtotal=200 where id=$2',[assignment,customer.id]);
    const ledger=async()=>(await db.query('select * from referral_ledger where id=$1',[customer.id])).rows[0];
    assert.equal((await ledger()).bonus_status,'pending');
    await db.query("update quickbooks_invoice_links set quickbooks_status='paid',quickbooks_balance=0,paid_at=now() where id=$1",[invoice]);
    assert.equal((await ledger()).bonus_status,'pending','prepayment alone does not earn a bonus');
    await db.query("update assignment_blocks set status='qa_pending' where id=$1",[assignment]);
    assert.equal((await ledger()).bonus_status,'pending','QA pending is not complete');
    await db.query("update assignment_blocks set status='completed' where id=$1",[assignment]);
    assert.equal((await ledger()).bonus_status,'earned');assert.equal(Number((await ledger()).bonus_amount),20);
    await db.query("update quickbooks_invoice_links set quickbooks_status='open',quickbooks_balance=50 where id=$1",[invoice]);
    assert.equal((await ledger()).bonus_status,'pending','partial/refunded payment is not eligible');
    await assert.rejects(db.query('select record_referral_payout($1,$2,$3)',[customer.id,'Check 123',actor]),/earned/);
    await db.query("update referral_customers set manual_paid_at=now(),payment_reference='Paid cash receipt 12' where id=$1",[customer.id]);
    assert.equal((await ledger()).bonus_status,'earned');
    await db.query('select record_referral_payout($1,$2,$3)',[customer.id,'Check 123',actor]);
    assert.equal((await ledger()).bonus_status,'paid');assert.equal(Number((await ledger()).payout_amount),20);
    await assert.rejects(db.query('select record_referral_payout($1,$2,$3)',[customer.id,'Duplicate',actor]),/earned/);
    await db.query("insert into assignment_blocks values($1,'completed',$2)",[randomUUID(),invoice]);
    assert.equal((await db.query('select count(*)::int as n from referral_ledger')).rows[0].n,1);
    const rows=[{name:'Imported',email:'a@example.com',phone:'+19195550120',city:'Raleigh',phone_1:'9195550121',email_2:'alt@example.com',source_key:'sheet:2'},{name:'Shared office',email:'a@example.com',phone:'+19195550120',city:'Durham',source_key:'sheet:3'},{name:'Western agent',city:'Asheville',source_key:'sheet:4'}];
    const imp=(await db.query('select import_referral_agents($1,$2) as result',[JSON.stringify(rows),actor])).rows[0].result;assert.equal(imp.imported,3);assert.equal(imp.duplicates,0);
    const repeat=(await db.query('select import_referral_agents($1,$2) as result',[JSON.stringify(rows),actor])).rows[0].result;assert.equal(repeat.imported,0);assert.equal(repeat.duplicates,3);
    assert.deepEqual((await db.query("select city from referral_agents where source_key is not null order by city_rank,city,name,id")).rows.map(r=>r.city),['Durham','Raleigh','Asheville']);
    const imported=(await db.query("select * from referral_agents where source_key='sheet:2'")).rows[0];assert.equal(imported.phone_1,'9195550121');assert.equal(imported.email_2,'alt@example.com');
    const prepared=(await db.query("update referral_agents set referral_code='TA-BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB' where id=$1 returning *",[imported.id])).rows[0];assert.equal(prepared.status,'new');assert.equal(prepared.activated_at,null);
    const later=(await db.query("update referral_agents set status='active' where id=$1 returning *",[imported.id])).rows[0];assert.ok(later.activated_at);assert.equal(later.referral_code,prepared.referral_code);
    for(let i=0;i<20;i++)assert.equal((await db.query("select allow_referral_request('test') as allowed")).rows[0].allowed,true);
    assert.equal((await db.query("select allow_referral_request('test') as allowed")).rows[0].allowed,false);
    await db.exec('set role anon');
    await assert.rejects(db.query('select * from referral_customers'),/permission denied/);
    await assert.rejects(db.query(register,[active.referral_code,'X','x@example.com','+19195550190','Main','Durham','']),/permission denied/);
    await db.exec('reset role;set role authenticated');
    await assert.rejects(db.query("update referral_agents set status='active'"),/permission denied/);
    await assert.rejects(db.query('select record_referral_payout($1,$2,$3)',[customer.id,'Bad',actor]),/permission denied/);
  }finally{await db.close();}
});
